[package]
name = "wow-alchemy-cdbc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/wow-alchemy-cdbc"
description = "Parser for World of Warcraft DBC (client database) files with serialization support"
readme = "README.md"
keywords = ["wow", "warcraft", "dbc", "database", "gamedev"]
categories = ["game-development", "parser-implementations"]

[dependencies]
thiserror = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true, optional = true }
log = { workspace = true }
clap = { workspace = true, optional = true }
memmap2 = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
directories = "6.0.0"
reqwest = { version = "0.12.23", features = ["blocking"] }
rusqlite = "0.37.0"

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
pretty_assertions = { workspace = true }
test-case = { workspace = true }

[features]
default = []
serde = ["dep:serde"]
mmap = ["dep:memmap2"]
parallel = ["dep:rayon"]

